Fix: Registry - Use custom domain instead of GitHub's domain
To correctly register the MCP server we MUST use a custom domain since the
server is not deployed under `github.io`.

> Error: publish failed: server returned status 400: {"title":"Bad
> Request","status":400,"detail":"Failed to publish
> server","errors":[{"message":"remote URL https://mcp.ai.teamwork.com does not
> match namespace io.github.Teamwork/mcp: remote URL host mcp.ai.teamwork.com
> does not match publisher domain Teamwork.github.io"}]}

https://github.com/modelcontextprotocol/registry/blob/773f09441ad8d9ce43c34957a7fb21d02e4bed5d/docs/guides/publishing/publish-server.md#step-3-configure-your-server-details